# Generated by Django 4.0 on 2022-02-18 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='song',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 2, 18, 19, 1, 49, 818776), max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playlist',
            name='duration',
            field=models.DurationField(),
        ),
    ]
